### ISSUE TITLE
Terminal won't stay open

### ISSUE THREAD

**Issue by lxgxiong** [jallwine/MSU-CSCI441-Spring-2015#2]
Does anyone have the same problem with me?
When I run the code, a terminal show up but it quits automatically a few seconds later, I don't even have enough time to type the inputs.

**Comment by jallwine** [comment]
Are you using Qt Creator in Windows? Some students have reported that adding the line CONFIG += console to the project file (lab1.pro) and then checking Run in Terminal under Projects (on the left side), Run (tab near the top).

**Comment by lxgxiong** [comment]
No, I am using Qt Creator in Mac. I can run it in terminal as you set the settings for me, but the terminal window just stays a few seconds.

**Comment by jallwine** [comment]
Ah, right. Have you tried adding CONFIG += console to the .pro file? It might still help in your situation, too.

**Comment by lxgxiong** [comment]
Yes, I did try this, and I found that the terminal quits, but the lab1 program is not actually stops, I can see it is running and I have to force quit the lab1 program. Below is what I can see in the terminal.

Leis-MacBook-Air:~ leixiong$ /Users/leixiong/msu-csci441-spring-2015/build-lab1-Desktop_Qt_5_4_0_clang_64bit-Debug/lab1.app/Contents/MacOS/lab1 ; exit;

**Comment by jallwine** [comment]
Hm, does it work if you just run it from the terminal directly?

**Comment by lxgxiong** [comment]
I just tried, it said qmake command not found. I am thinking maybe it is a environment variables problem.

**Comment by jallwine** [comment]
I meant can you just run the executable that Qt Creator built:
/Users/leixiong/msu-csci441-spring-2015/build-lab1-Desktop_Qt_5_4_0_clang_64bit-Debug/lab1.app/Contents/MacOS/lab1

**Comment by JesseStephenBrown** [comment]
The instructions are poor for installing qt, in that it does NOT correctly symlink /usr/bin/qmake with your installation of qmake or, in your case, doesn't make that symlink. To resolve qmake command not found, you can either:

1. Symlink using `ln -s` (see the man page for ln for help) your qmake binary to a directory in your path, such as /usr/local/bin OR
2. Add the folder containing the qt binaries, which for 5.4 is `/path/to/Qt/5.4/clang_64/bin` . Note that if you are using gcc or a different compiler the clang_64 folder may be something else. Also, you may not have downloaded 5.4, so the version folder will be the version you installed.

**Comment by alancleary** [comment]
If you don't mind compiling and running your programs in the terminal I
recommend installing qt with brew.

Install brew as explained here

http://brew.sh/

and then run

brew install qt

then you should be able to compiling and run your program in the terminal
with

qmake
make
./lab1

**Comment by jallwine** [comment]
One concern with using brew to install qt is you'll get qt4. I've had more success Qt 5 and OpenGL out of the box.

**Comment by alancleary** [comment]
Good point. It turns out you need to explicitly tell brew to install Qt 5

brew install qt5

Then you need to add it to your path (mine installed to /usr/local/Cellar/qt5).
